#%RAML 1.0 ResourceType
post?:
  responses:
    400:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    401:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    403:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    404:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    422:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    500:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    501:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    503:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    504:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
          
put?:
  responses:
    400:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    401:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    403:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    404:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    422:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    500:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    501:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    503:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    504:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
          
get?:
  responses:
    400:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    401:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    403:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    404:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    422:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    500:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    501:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    503:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>
    504:
      body:
        application/json:
          type: <<errors-schema>>
          example: <<errors-example>>